// packages/vue/src/lib/components/SkeletonizerSkeleton.vue
<script setup lang="ts" generic="TSkeletonScopeObject extends object">
import { type ISkeletonizerColorSchema, SkeletonAdapterComponent, type TSchemaConfig } from '@skeletonizer/utils';
import { reactive, type UnwrapNestedRefs, type UnwrapRef, watch } from 'vue';

const props: Readonly<{
  config: TSchemaConfig<TSkeletonScopeObject>;
  showSkeleton: boolean;
  scope: TSkeletonScopeObject;
  colorSchema?: ISkeletonizerColorSchema;
}> = defineProps<{
  config: TSchemaConfig<TSkeletonScopeObject>;
  showSkeleton: boolean;
  scope: TSkeletonScopeObject;
  colorSchema?: ISkeletonizerColorSchema;
}>();

defineSlots<{
  default?: (props: { scope: TSkeletonScopeObject | UnwrapRef<TSkeletonScopeObject> }) => {
    scope: TSkeletonScopeObject | UnwrapRef<TSkeletonScopeObject>;
  };
}>();

const component: UnwrapNestedRefs<SkeletonAdapterComponent<TSkeletonScopeObject>>
  = reactive(new SkeletonAdapterComponent<TSkeletonScopeObject>());

watch(
  props.config,
  (config: TSchemaConfig<TSkeletonScopeObject>) => {
    component.config = config;
    component.setupModels();
  },
  { immediate: true },
);
</script>

<template>
  <template v-if="showSkeleton">
    <div
      v-for="(model, index) of component.viewModels"
      :key="index"
      v-skeletonize="props.colorSchema"
    >
      <slot :scope="model.value" />
    </div>
  </template>

  <slot
    v-else
    :scope="props.scope"
  />
</template>

<style lang="scss">
@use '@skeletonizer/styles';
</style>

// packages/angular/projects/skeletonizer/src/lib/skeletonizer.skeleton.component.ts
import { Component, ContentChild, Input, TemplateRef, ViewEncapsulation } from '@angular/core';
import { ISkeletonizerColorSchema, Schema, SkeletonAdapterComponent, TSchemaConfig } from '@skeletonizer/utils';

@Component({
  selector: 'skeletonizer-skeleton',
  templateUrl: './skeletonizer.skeleton.component.html',
  styleUrls: ['./skeletonizer.skeleton.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class SkeletonizerSkeletonComponent<T extends object, Scope extends T> extends SkeletonAdapterComponent<T> {
  @ContentChild(TemplateRef) public readonly templateRef!: TemplateRef<{ $implicit: Schema<T> | Scope }>;

  @Input({ required: true }) public showSkeleton!: boolean;
  @Input({ required: true }) public scope!: Scope;
  @Input() public colorSchema?: ISkeletonizerColorSchema;

  @Input({ alias: 'config', required: true }) public set configInput(config: TSchemaConfig<T>) {
    this.config = config;

    this.setupModels();
  }
}

<ng-container *ngIf="showSkeleton">
  <ng-container *ngFor="let model of viewModels">
    <div [skeletonize]="colorSchema">
      <ng-container *ngTemplateOutlet="templateRef; context: { $implicit: model }"></ng-container>
    </div>
  </ng-container>
</ng-container>

<ng-container *ngIf="!showSkeleton">
  <ng-container *ngTemplateOutlet="templateRef; context: { $implicit: scope }"></ng-container>
</ng-container>
